// Curated CET-4 examples (from 大学英语四级例句.txt, 547 entries)
// word -> { e: English (concrete, <=12 words), c: Chinese (colloquial) }
const CURATED = {
  "plastic": { e: "This plastic bottle can be recycled after use.", c: "这个塑料瓶用完后可以回收。" },
  "steal": { e: "Someone stole my wallet on the bus yesterday.", c: "昨天有人在公交车上偷了我的钱包。" },
  "preferable": { e: "Taking the subway is preferable to driving in rush hour.", c: "高峰期坐地铁比开车更好。" },
  "summarize": { e: "Can you summarize the main points of the meeting?", c: "你能概括一下这次会议的要点吗？" },
  "chart": { e: "The chart shows our sales growth over the past year.", c: "这张图表显示了我们过去一年的销售增长。" },
  "student": { e: "She is a first-year student majoring in engineering.", c: "她是一名工程专业的大一学生。" },
  "lip": { e: "She put some lip balm on before going out.", c: "她出门前涂了点润唇膏。" },
  "year": { e: "He spent a year studying abroad in Australia.", c: "他在澳大利亚留学了一年。" },
  "consistent": { e: "You need to be consistent with your exercise routine.", c: "你需要坚持你的锻炼计划。" },
  "maintenance": { e: "The building is closed for regular maintenance this weekend.", c: "大楼本周末因例行维护关闭。" },
  "comrade": { e: "My old comrade from the army called me last night.", c: "我部队的老战友昨晚给我打了电话。" },
  "approach": { e: "You should approach the problem step by step.", c: "你应该一步一步地处理这个问题。" },
  "phase": { e: "The project will enter the testing phase next month.", c: "项目下个月将进入测试阶段。" },
  "moan": { e: "He let out a moan when he saw the bill.", c: "他看到账单时呻吟了一声。" },
  "american": { e: "She married an American and moved to New York.", c: "她嫁给了一个美国人，搬去了纽约。" },
  "approximate": { e: "The approximate cost of the repair is around 500 yuan.", c: "维修的大概费用在500元左右。" },
  "attend": { e: "All employees must attend the safety training session.", c: "所有员工必须参加安全培训。" },
  "radiate": { e: "The heater radiates warmth throughout the room.", c: "暖气片向整个房间辐射热量。" },
  "predict": { e: "Experts predict rain for the weekend.", c: "专家预测周末会下雨。" },
  "harbour": { e: "The fishing boats returned to the harbour before sunset.", c: "渔船在日落前返回了港口。" },
  "box": { e: "I packed all my books into a cardboard box.", c: "我把所有书都装进了一个纸箱里。" },
  "type": { e: "What type of music do you usually listen to?", c: "你平时听什么类型的音乐？" },
  "bucket": { e: "She filled a bucket with water to wash the floor.", c: "她装满了一桶水来拖地。" },
  "evening": { e: "Let's grab dinner together this evening.", c: "今晚咱们一起吃个饭吧。" },
  "adjective": { e: "Choose an adjective that best describes your feeling.", c: "选一个最能描述你感受的形容词。" },
  "sweat": { e: "He wiped the sweat from his forehead after the run.", c: "跑完步后他擦了擦额头上的汗。" },
  "exactly": { e: "Tell me exactly what happened at the meeting.", c: "确切地告诉我会议上发生了什么。" },
  "daily": { e: "I try to read for at least 30 minutes on a daily basis.", c: "我尽量每天至少阅读30分钟。" },
  "trim": { e: "He asked the barber to trim his beard.", c: "他让理发师帮他修一下胡子。" },
  "nevertheless": { e: "It was raining hard; nevertheless, they went out for a walk.", c: "雨下得很大，不过他们还是出去散步了。" },
  "storage": { e: "We need more storage space for the new equipment.", c: "我们需要更多存储空间来放新设备。" },
  "typist": { e: "She worked as a typist at the law firm for three years.", c: "她在律师事务所做了三年打字员。" },
  "central": { e: "The hotel is located in the central area of the city.", c: "酒店位于市中心区域。" },
  "entrance": { e: "Please wait for me at the main entrance of the mall.", c: "请在商场正门口等我。" },
  "sensible": { e: "It's sensible to save some money for emergencies.", c: "存点钱以备急用是明智的。" },
  "career": { e: "She started her career as a teacher right after college.", c: "她大学毕业后就开始了教师生涯。" },
  "automobile": { e: "The automobile industry is shifting toward electric cars.", c: "汽车行业正在向电动汽车转型。" },
  "p.m.": { e: "The meeting is scheduled for 3:00 P.M. this afternoon.", c: "会议定在今天下午三点。" },
  "professor": { e: "The professor explained the theory with a simple example.", c: "教授用一个简单的例子解释了那个理论。" },
  "dumb": { e: "Don't call yourself dumb; you just need more practice.", c: "别说自己笨，你只是需要多练习。" },
  "delay": { e: "The flight was delayed due to bad weather.", c: "航班因天气不好延误了。" },
  "gloomy": { e: "The weather has been gloomy all week.", c: "这一周天气都阴沉沉的。" },
  "cripple": { e: "The accident crippled his left leg permanently.", c: "那次事故永久性地残废了他的左腿。" },
  "intellectual": { e: "Reading books is a good way to satisfy your intellectual curiosity.", c: "读书是满足求知欲的好方法。" },
  "wake": { e: "I set my alarm to wake me up at six every morning.", c: "我每天设闹钟六点叫醒自己。" },
  "extent": { e: "To what extent do you agree with this decision?", c: "你在多大程度上同意这个决定？" },
  "roast": { e: "My mom is roasting a chicken in the oven for dinner.", c: "我妈正在烤箱里烤鸡准备晚餐。" },
  "ripe": { e: "The bananas are not ripe enough to eat yet.", c: "香蕉还没熟透，不能吃。" },
  "academic": { e: "Her academic performance has improved a lot this semester.", c: "她这学期的学习成绩提高了很多。" },
  "headquarters": { e: "The company moved its headquarters to Shanghai last year.", c: "公司去年把总部搬到了上海。" },
  "whom": { e: "Whom did you invite to the party on Saturday?", c: "你周六的派对上邀请了谁？" },
  "render": { e: "The heavy rain rendered the roads impassable for hours.", c: "大雨使道路数小时无法通行。" },
  "launch": { e: "The company will launch a new smartphone next month.", c: "公司下个月将推出一款新手机。" },
  "serve": { e: "This restaurant serves breakfast from seven to ten.", c: "这家餐厅从七点到十点供应早餐。" },
  "comparative": { e: "The article offers a comparative analysis of the two systems.", c: "这篇文章对这两个系统进行了比较分析。" },
  "wolf": { e: "A wolf was spotted near the village last winter.", c: "去年冬天有人在村子附近发现了一只狼。" },
  "japan": { e: "She traveled to Japan to study the language and culture.", c: "她去日本学习语言和文化。" },
  "whose": { e: "Whose phone is ringing in the meeting room?", c: "会议室里是谁的手机在响？" },
  "support": { e: "My parents always support my decisions no matter what.", c: "我爸妈不管怎样都支持我的决定。" },
  "move": { e: "We need to move the table to make space for the sofa.", c: "我们得挪一下桌子给沙发腾地方。" },
  "weave": { e: "She learned to weave baskets from her grandmother.", c: "她跟奶奶学会了编篮子。" },
  "hill": { e: "They climbed to the top of the hill to watch the sunrise.", c: "他们爬到山顶去看日出。" },
  "content": { e: "Are you content with your current salary and job?", c: "你对你现在的工资和工作满意吗？" },
  "place": { e: "This seems like a nice place to have a picnic.", c: "这地方看起来很适合野餐。" },
  "conclusion": { e: "In conclusion, I believe the plan is worth trying.", c: "总之，我认为这个计划值得一试。" },
  "man": { e: "A young man helped me carry the groceries upstairs.", c: "一个年轻男人帮我把东西搬上了楼。" },
  "cost": { e: "How much does a ticket to Beijing cost these days?", c: "最近去北京的票多少钱一张？" },
  "ratio": { e: "The ratio of boys to girls in this class is three to two.", c: "这个班男女生的比例是三比二。" },
  "arabian": { e: "She rode an Arabian horse across the desert landscape.", c: "她骑着一匹阿拉伯马穿越了沙漠。" },
  "construction": { e: "The construction of the new bridge will take two years.", c: "新桥的建造将耗时两年。" },
  "except": { e: "The library is open every day except Monday.", c: "图书馆除周一外每天都开放。" },
  "section": { e: "Please turn to the sports section of the newspaper.", c: "请翻到报纸的体育版。" },
  "bulb": { e: "I need to replace the light bulb in the hallway.", c: "我需要换一下走廊的灯泡。" },
  "buy": { e: "I want to buy a new laptop before the semester starts.", c: "我想在开学前买一台新笔记本电脑。" },
  "bell": { e: "The school bell rings at eight o'clock every morning.", c: "学校每天早上八点打铃。" },
  "woollen": { e: "She wore a thick woollen scarf to keep warm.", c: "她围了一条厚羊毛围巾来保暖。" },
  "cave": { e: "The tour guide led us into a dark limestone cave.", c: "导游带我们走进了一个黑暗的石灰岩洞穴。" },
  "chemist": { e: "The chemist mixed two liquids to start the reaction.", c: "化学家混合了两种液体来启动反应。" },
  "definition": { e: "Can you give me a clear definition of this term?", c: "你能给我这个词的明确定义吗？" },
  "weight": { e: "I've gained some weight during the winter holiday.", c: "寒假期间我长胖了一些。" },
  "robbery": { e: "The police caught the suspect within hours of the robbery.", c: "抢劫案发生后几小时内警察就抓住了嫌疑犯。" },
  "civilize": { e: "Schools play a key role in educating and civilizing children.", c: "学校在教育孩子和使他们有教养方面起关键作用。" },
  "reap": { e: "If you work hard now, you will reap the rewards later.", c: "现在努力，以后就会有收获。" },
  "cinema": { e: "Let's go to the cinema to watch the new action movie.", c: "咱们去电影院看那部新动作片吧。" },
  "recommendation": { e: "I bought this phone based on a friend's recommendation.", c: "我是听了朋友的推荐才买了这部手机。" },
  "data": { e: "The data shows a steady increase in online sales.", c: "数据表明线上销售在稳步增长。" },
  "ought": { e: "You ought to apologize for what you said earlier.", c: "你应该为你刚才说的话道歉。" },
  "objection": { e: "Does anyone have any objection to the new schedule?", c: "有人对新时间表有异议吗？" },
  "doctor": { e: "The doctor advised him to get more rest and drink water.", c: "医生建议他多休息、多喝水。" },
  "slide": { e: "The kids love to slide down the big yellow slide.", c: "孩子们喜欢从那个黄色大滑梯上滑下来。" },
  "loan": { e: "He took out a loan to pay for his college tuition.", c: "他贷了一笔款来支付大学学费。" },
  "applicable": { e: "This discount is only applicable to purchases over 200 yuan.", c: "这个折扣仅适用于满200元的购物。" },
  "hate": { e: "I hate getting up early on cold winter mornings.", c: "我讨厌在寒冷的冬天早上早起。" },
  "hostess": { e: "The flight hostess offered us blankets and drinks.", c: "空姐给我们拿来了毯子和饮料。" },
  "leap": { e: "The cat made a sudden leap onto the kitchen counter.", c: "那只猫突然一跃跳上了厨房台面。" },
  "distance": { e: "The distance between the two cities is about 300 kilometers.", c: "这两个城市之间的距离大约是300公里。" },
  "pronounce": { e: "Could you tell me how to pronounce this word correctly?", c: "你能告诉我这个词怎么正确发音吗？" },
  "oriental": { e: "The shop sells oriental tea sets and handmade ceramics.", c: "这家店出售东方茶具和手工陶瓷。" },
  "beat": { e: "Our team beat the defending champions by two points.", c: "我们队以两分之差击败了卫冕冠军。" },
  "affair": { e: "He refused to comment on his personal affairs.", c: "他拒绝谈论自己的私事。" },
  "sponge": { e: "Use a wet sponge to wipe the table after dinner.", c: "吃完饭后用湿海绵擦一下桌子。" },
  "chief": { e: "The chief engineer explained the design to the team.", c: "总工程师向团队解释了设计方案。" },
  "snake": { e: "Be careful — there might be snakes in the tall grass.", c: "小心点——草丛里可能有蛇。" },
  "classroom": { e: "Please turn off your phone before entering the classroom.", c: "进教室前请把手机关掉。" },
  "signature": { e: "You need to put your signature at the bottom of the form.", c: "你需要在表格底部签上你的名字。" },
  "absolutely": { e: "I absolutely love the coffee at this little café.", c: "我超爱这家小咖啡馆的咖啡。" },
  "boundary": { e: "The river marks the boundary between the two towns.", c: "这条河是两座城镇的分界线。" },
  "crawl": { e: "The baby just learned to crawl across the living room floor.", c: "宝宝刚学会在客厅地板上爬。" },
  "sharpen": { e: "Can you sharpen this pencil before the exam starts?", c: "考试开始前你能把这支铅笔削好吗？" },
  "acid": { e: "The lemon juice contains a high level of citric acid.", c: "柠檬汁含有高浓度的柠檬酸。" },
  "complicated": { e: "The instructions are too complicated for me to follow.", c: "这个说明书太复杂了，我看不懂。" },
  "missing": { e: "My keys are missing — have you seen them anywhere?", c: "我的钥匙不见了——你在哪儿看到过吗？" },
  "maths": { e: "She helps her little brother with his maths homework every night.", c: "她每天晚上辅导弟弟做数学作业。" },
  "area": { e: "There is a nice picnic area near the lake.", c: "湖边有一个不错的野餐区。" },
  "tuition": { e: "The university raised tuition fees by five percent this year.", c: "这所大学今年把学费涨了百分之五。" },
  "beard": { e: "He decided to grow a beard during the winter break.", c: "他决定在寒假期间蓄胡子。" },
  "fortunately": { e: "I missed the bus, but fortunately a friend gave me a ride.", c: "我没赶上公交，但幸好有个朋友捎了我一程。" },
  "o'clock": { e: "I'll meet you at the station at six o'clock sharp.", c: "我六点整在车站跟你碰面。" },
  "none": { e: "None of the students knew the answer to that question.", c: "没有一个学生知道那个问题的答案。" },
  "reader": { e: "She is an avid reader and finishes a book every week.", c: "她是个书迷，每周能读完一本书。" },
  "bar": { e: "There's a nice coffee bar just around the corner.", c: "拐角处就有一家不错的咖啡吧。" },
  "farmer": { e: "The farmer gets up before sunrise to feed the animals.", c: "农民日出前就起床去喂牲口了。" },
  "entertain": { e: "The clown tried to entertain the kids with funny tricks.", c: "小丑试图用有趣的把戏逗孩子们开心。" },
  "nor": { e: "He neither called nor sent a message to explain his absence.", c: "他既没打电话也没发消息来解释为什么没来。" },
  "world": { e: "Traveling opens your eyes to the world around you.", c: "旅行能开阔你对世界的眼界。" },
  "capable": { e: "She is more than capable of handling this project alone.", c: "她完全有能力独立处理这个项目。" },
  "mercy": { e: "The injured bird was at the mercy of the hungry cat.", c: "那只受伤的鸟完全在饿猫的摆布之下。" },
  "refreshment": { e: "Light refreshments will be served after the lecture.", c: "讲座结束后会提供简单茶点。" },
  "staircase": { e: "She tripped and fell down the staircase in the dark.", c: "她在黑暗中绊了一跤，从楼梯上摔了下去。" },
  "capital": { e: "Beijing is the capital of China and a city full of history.", c: "北京是中国的首都，也是一座充满历史的城市。" },
  "sadly": { e: "He shook his head sadly and walked away without a word.", c: "他伤心地摇了摇头，一言不发地走开了。" },
  "stumble": { e: "I stumbled over a rock while jogging in the park.", c: "我在公园跑步时被一块石头绊倒了。" },
  "finally": { e: "After hours of waiting, the bus finally arrived.", c: "等了几个小时后，公交车终于来了。" },
  "suffer": { e: "Many people suffer from back pain due to long hours of sitting.", c: "很多人因为久坐而受背痛之苦。" },
  "instant": { e: "The instant I walked in, I knew something was wrong.", c: "我一走进去就立刻感觉到不对劲。" },
  "miner": { e: "The miner spent eight hours underground digging for coal.", c: "矿工在地下挖煤待了八个小时。" },
  "quote": { e: "He began his speech with a famous quote from Einstein.", c: "他用一句爱因斯坦的名言开始了演讲。" },
  "meadow": { e: "The children ran through the meadow chasing butterflies.", c: "孩子们跑过草地追逐蝴蝶。" },
  "understand": { e: "I don't understand why he quit such a good job.", c: "我不理解他为什么辞掉这么好的一份工作。" },
  "disclose": { e: "The company refused to disclose the details of the deal.", c: "公司拒绝透露这笔交易的细节。" },
  "acceptance": { e: "She received a letter of acceptance from the university.", c: "她收到了那所大学的录取通知书。" },
  "substance": { e: "The scientist identified a strange substance in the water sample.", c: "科学家在水样中发现了一种奇怪物质。" },
  "whitewash": { e: "They tried to whitewash the scandal before the election.", c: "他们试图在选举前掩盖这桩丑闻。" },
  "ridiculous": { e: "You look ridiculous wearing that hat indoors.", c: "你在屋里戴着那顶帽子看起来太滑稽了。" },
  "desk": { e: "Please clear everything off your desk before leaving the office.", c: "离开办公室前请把桌面收拾干净。" },
  "opportunity": { e: "This internship is a great opportunity to gain real experience.", c: "这次实习是获得实际经验的绝佳机会。" },
  "draw": { e: "The little girl loves to draw pictures of her family.", c: "那个小女孩喜欢画她的家人。" },
  "lead": { e: "Too much stress can lead to serious health problems.", c: "压力太大可能导致严重的健康问题。" },
  "track": { e: "The app helps you track your daily calorie intake.", c: "这个应用帮你记录每天的卡路里摄入量。" },
  "b.c.": { e: "The Great Wall was first built around 200 B.C.", c: "长城最早建于公元前200年左右。" },
  "sake": { e: "For the sake of your health, you should quit smoking.", c: "为了你的健康着想，你应该戒烟。" },
  "building": { e: "The office building has a coffee shop on the ground floor.", c: "这栋办公楼的一楼有一家咖啡店。" },
  "metre": { e: "The swimming pool is 25 metres long and 10 metres wide.", c: "这个游泳池长25米、宽10米。" },
  "overhead": { e: "Please put your luggage in the overhead compartment.", c: "请把行李放在头顶上方的行李架里。" },
  "kneel": { e: "He knelt down to tie his daughter's shoelaces.", c: "他跪下来给女儿系鞋带。" },
  "jump": { e: "The dog jumped over the fence and ran into the garden.", c: "狗跳过栅栏跑进了花园。" },
  "spread": { e: "News of the accident spread quickly through the town.", c: "事故的消息很快传遍了整个小镇。" },
  "right": { e: "You made the right decision by not driving in the storm.", c: "你决定不在暴风雨里开车是对的。" },
  "insufficient": { e: "His application was rejected due to insufficient experience.", c: "他的申请因为经验不足被拒了。" },
  "gross": { e: "The company reported a gross profit of two million dollars.", c: "公司报告了200万美元的毛利润。" },
  "desire": { e: "She has a strong desire to travel around the world.", c: "她有一个强烈的愿望，想要环游世界。" },
  "piano": { e: "He practices the piano for an hour every evening after dinner.", c: "他每天晚饭后练一小时钢琴。" },
  "medium": { e: "Would you like your steak in small, medium, or large size?", c: "您的牛排要小份、中份还是大份？" },
  "make": { e: "Let me make you a cup of hot tea to warm you up.", c: "我给你泡杯热茶暖暖身子吧。" },
  "minimum": { e: "The minimum wage in this city is rising next year.", c: "这个城市的最低工资明年要涨了。" },
  "lucky": { e: "You're so lucky to find a parking spot right outside the door.", c: "你太幸运了，在门口就找到了停车位。" },
  "shopkeeper": { e: "The shopkeeper gave me a discount because I'm a regular customer.", c: "店主给我打了折，因为我是老顾客。" },
  "rice": { e: "Could you cook some rice to go with the chicken?", c: "你能煮点米饭配鸡肉吗？" },
  "origin": { e: "The origin of this tradition dates back over a thousand years.", c: "这个传统的起源可以追溯到一千多年前。" },
  "stir": { e: "Stir the soup gently so it doesn't spill over the pot.", c: "轻轻搅拌汤，别让它溢出锅来。" },
  "nowadays": { e: "Nowadays most people use their phones to pay for things.", c: "现在大多数人用手机来付钱。" },
  "aircraft": { e: "The aircraft landed safely despite the strong wind and rain.", c: "尽管风雨很大，飞机还是安全降落了。" },
  "outdoors": { e: "Kids today spend less time playing outdoors than before.", c: "现在的孩子户外玩耍的时间比以前少了。" },
  "helmet": { e: "Always wear a helmet when riding a bike on the road.", c: "骑车上路时一定要戴头盔。" },
  "dial": { e: "Pick up the phone and dial the number I just gave you.", c: "拿起电话拨我刚才给你的号码。" },
  "enthusiasm": { e: "The new teacher showed great enthusiasm for her subject.", c: "新老师对她的学科表现出极大的热情。" },
  "wavelength": { e: "Radio waves travel at a certain wavelength through the air.", c: "无线电波以特定的波长在空气中传播。" },
  "queer": { e: "There was a queer smell coming from the basement.", c: "地下室里传来一股奇怪的味道。" },
  "fancy": { e: "Do you fancy going out for a walk after dinner?", c: "晚饭后你想出去散散步吗？" },
  "cock": { e: "The cock crowed loudly at the break of dawn.", c: "公鸡在破晓时分大声啼叫。" },
  "robot": { e: "The factory now uses robots to assemble car parts.", c: "这家工厂现在用机器人来组装汽车零件。" },
  "top": { e: "She placed the book on the top shelf of the bookcase.", c: "她把书放在了书架最上面的一层。" },
  "cake": { e: "My grandma baked a chocolate cake for my birthday.", c: "奶奶为我的生日烤了一个巧克力蛋糕。" },
  "toy": { e: "The little boy refused to share his toy truck with his sister.", c: "小男孩不肯跟妹妹分享他的玩具卡车。" },
  "state": { e: "The roads are in a terrible state after the heavy snow.", c: "大雪过后，路况非常糟糕。" },
  "classical": { e: "She listens to classical music while studying in the library.", c: "她在图书馆学习时听古典音乐。" },
  "imagination": { e: "A good story can fire up a child's imagination.", c: "一个好故事能激发孩子的想象力。" },
  "messenger": { e: "The messenger delivered the package to my office this morning.", c: "快递员今天早上把包裹送到了我的办公室。" },
  "clothes": { e: "She folded the clean clothes and put them in the closet.", c: "她把干净衣服叠好放进了衣柜里。" },
  "basic": { e: "Learning a few basic phrases can help you when traveling abroad.", c: "学几句基本用语在出国旅行时很有用。" },
  "lorry": { e: "The lorry was loaded with fresh vegetables for the market.", c: "卡车上装满了运往市场的新鲜蔬菜。" },
  "vague": { e: "His answer was too vague for me to understand what he meant.", c: "他的回答太含糊了，我搞不懂他什么意思。" },
  "pile": { e: "There is a pile of dirty laundry on the bathroom floor.", c: "浴室地板上有一堆脏衣服。" },
  "proceed": { e: "After the break, we will proceed with the next topic on the agenda.", c: "休息后，我们将继续讨论议程上的下一个话题。" },
  "illness": { e: "She missed a whole month of school due to a serious illness.", c: "她因为一场重病缺了整整一个月的课。" },
  "inevitable": { e: "A certain amount of stress is inevitable in modern life.", c: "现代生活中一定程度的压力是不可避免的。" },
  "deceive": { e: "He tried to deceive customers into buying fake products.", c: "他试图欺骗顾客购买假冒产品。" },
  "as": { e: "As I was leaving the house, the phone suddenly rang.", c: "我正要出门时，电话突然响了。" },
  "loaf": { e: "I bought a fresh loaf of bread from the bakery this morning.", c: "我今早在面包店买了一条新鲜面包。" },
  "stare": { e: "It's rude to stare at people you don't know.", c: "盯着陌生人看是不礼貌的。" },
  "jacket": { e: "You'd better bring a jacket; it gets cold in the evening.", c: "你最好带件外套，晚上会变凉。" },
  "stiffen": { e: "His muscles stiffened after sitting in the car for six hours.", c: "在车里坐了六小时后，他的肌肉都僵硬了。" },
  "forecast": { e: "The weather forecast says it will snow tomorrow morning.", c: "天气预报说明天早上会下雪。" },
  "accent": { e: "He speaks English with a slight French accent.", c: "他讲英语带点法语口音。" },
  "collapse": { e: "The old bridge collapsed under the weight of the truck.", c: "那座旧桥在卡车的重压下坍塌了。" },
  "belt": { e: "Please fasten your seat belt before the car starts moving.", c: "车开动前请系好安全带。" },
  "crew": { e: "The flight crew welcomed passengers on board with a smile.", c: "机组人员微笑着欢迎乘客登机。" },
  "start": { e: "I usually start my day with a cup of black coffee.", c: "我通常以一杯黑咖啡开始新的一天。" },
  "legend": { e: "According to the legend, a dragon once lived in this lake.", c: "传说这个湖里曾经住着一条龙。" },
  "lump": { e: "She found a small lump on her neck and went to see a doctor.", c: "她发现脖子上有个小肿块，就去看了医生。" },
  "talent": { e: "He has a natural talent for playing the guitar by ear.", c: "他天生有靠耳朵听就能弹吉他的天赋。" },
  "scout": { e: "The scout went ahead to check the condition of the trail.", c: "侦察员先行一步去查看路况。" },
  "river": { e: "The kids love to skip stones across the river on weekends.", c: "孩子们周末喜欢在河面上打水漂。" },
  "resistance": { e: "The new material has high resistance to heat and water.", c: "这种新材料耐高温且防水。" },
  "a.m.": { e: "The meeting starts at 9:00 a.m., so please don't be late.", c: "会议上午九点开始，请别迟到。" },
  "remarkable": { e: "She made remarkable progress in her English speaking skills.", c: "她的英语口语进步非常明显。" },
  "ill": { e: "He called in sick because he felt too ill to go to work.", c: "他请病假了，因为他病得没法去上班。" },
  "indignant": { e: "She was indignant when she found out someone had lied to her.", c: "她发现有人骗了她时非常气愤。" },
  "portuguese": { e: "He ordered a Portuguese red wine to go with the steak.", c: "他点了一瓶葡萄牙红酒来配牛排。" },
  "brass": { e: "The old doorknob was made of polished brass.", c: "那个旧门把手是抛光黄铜做的。" },
  "measure": { e: "The tailor measured my waist and chest for the new suit.", c: "裁缝为我量了腰围和胸围来做新西装。" },
  "department": { e: "The HR department is on the third floor of this building.", c: "人力资源部在这栋楼的三楼。" },
  "excursion": { e: "The school organized an excursion to the science museum.", c: "学校组织了一次去科学博物馆的短途旅行。" },
  "intelligence": { e: "The test is designed to measure a child's verbal intelligence.", c: "这个测试旨在衡量孩子的语言智力。" },
  "put": { e: "Please put the milk back in the fridge after you use it.", c: "用完后请把牛奶放回冰箱里。" },
  "deny": { e: "He denied breaking the window, but no one believed him.", c: "他否认打破了窗户，但没人信他。" },
  "yield": { e: "The apple tree in our yard yields plenty of fruit every autumn.", c: "我们院子里的苹果树每年秋天结很多果子。" },
  "poisonous": { e: "Be careful—some mushrooms in the forest are highly poisonous.", c: "小心——森林里有些蘑菇有剧毒。" },
  "not": { e: "I'm not sure if the store is still open at this hour.", c: "我不确定这个时间商店还开不开门。" },
  "monthly": { e: "The magazine is published on a monthly basis and costs five yuan.", c: "这本杂志是月刊，每本五块钱。" },
  "outside": { e: "It's raining outside, so take an umbrella with you.", c: "外面在下雨，带把伞吧。" },
  "mirror": { e: "She checked her hair in the mirror before leaving the house.", c: "她出门前对着镜子整理了一下头发。" },
  "scene": { e: "The police arrived at the scene within ten minutes.", c: "警察十分钟内赶到了现场。" },
  "drama": { e: "The drama series has been popular among young viewers this year.", c: "这部电视剧今年在年轻观众中很受欢迎。" },
  "accordingly": { e: "The weather was terrible, and we adjusted our plans accordingly.", c: "天气很糟糕，我们相应地调整了计划。" },
  "operate": { e: "Do you know how to operate this washing machine?", c: "你知道怎么操作这台洗衣机吗？" },
  "glove": { e: "She put on a pair of thick gloves before shoveling the snow.", c: "她铲雪前戴上了一双厚手套。" },
  "frog": { e: "We could hear frogs croaking loudly by the pond at night.", c: "晚上我们能听到池塘边青蛙呱呱叫。" },
  "bean": { e: "She added some red beans to the soup for extra flavor.", c: "她往汤里加了些红豆来增加风味。" },
  "waterproof": { e: "You need a waterproof jacket if you're hiking in the rain.", c: "如果要在雨中徒步，你需要一件防水外套。" },
  "smoke": { e: "There's too much smoke in the kitchen—open the window!", c: "厨房里烟太大了——快开窗！" },
  "seize": { e: "The police seized a large amount of illegal drugs at the border.", c: "警察在边境查获了大量毒品。" },
  "hotel": { e: "We booked a hotel near the train station to save time.", c: "我们订了火车站附近的酒店以节省时间。" },
  "abroad": { e: "She has always dreamed of studying abroad in the United States.", c: "她一直梦想去美国留学。" },
  "saucer": { e: "He placed the teacup gently on the saucer to avoid spilling.", c: "他轻轻把茶杯放在茶托上以免洒出来。" },
  "collective": { e: "The success of the project was a collective effort of the whole team.", c: "这个项目的成功是团队集体努力的结果。" },
  "enlarge": { e: "Click on the image to enlarge it and see the details.", c: "点击图片可以放大查看细节。" },
  "music": { e: "I like to listen to soft music before going to sleep at night.", c: "我喜欢晚上睡觉前听点轻柔的音乐。" },
  "highway": { e: "We took the highway to avoid the heavy traffic in the city.", c: "我们走高速绕开了市区的拥堵。" },
  "bronze": { e: "The athlete won a bronze medal in the national swimming competition.", c: "那位运动员在全国游泳比赛中获得了一枚铜牌。" },
  "broom": { e: "She swept the kitchen floor with a broom after cooking dinner.", c: "做完晚饭后她用扫帚扫了厨房的地。" },
  "eighty": { e: "My grandmother is eighty years old but still walks every day.", c: "我奶奶八十岁了，但每天还坚持散步。" },
  "tidy": { e: "Please tidy up your room before the guests arrive.", c: "客人来之前请把你的房间收拾一下。" },
  "stiff": { e: "My neck feels stiff after sleeping in a wrong position last night.", c: "昨晚睡姿不对，今天脖子僵硬得很。" },
  "accurate": { e: "Make sure all the figures in the report are accurate and up to date.", c: "确保报告中的所有数字都准确且是最新的。" },
  "receipt": { e: "Keep the receipt in case you need to return the item later.", c: "把收据留好，以防之后需要退货。" },
  "hand": { e: "Could you give me a hand with moving this heavy box?", c: "你能帮我搬一下这个重箱子吗？" },
  "near": { e: "There's a convenience store near our apartment building.", c: "我们公寓楼附近有一家便利店。" },
  "curiosity": { e: "The little boy opened the box out of curiosity to see what was inside.", c: "小男孩出于好奇打开盒子看看里面是什么。" },
  "sudden": { e: "All of a sudden, the lights went out in the whole building.", c: "突然之间，整栋楼的灯全灭了。" },
  "cousin": { e: "My cousin is coming to visit us during the summer holiday.", c: "我表妹暑假要来看我们。" },
  "accumulate": { e: "Dust tends to accumulate on the bookshelf if you don't clean it often.", c: "书架如果不常打扫，就会积灰。" },
  "probable": { e: "It is highly probable that the train will be delayed due to the storm.", c: "由于暴风雨，火车很可能会晚点。" },
  "eleven": { e: "The store opens at eleven in the morning and closes at nine at night.", c: "这家店上午十一点开门，晚上九点关门。" },
  "govern": { e: "The country is governed by a president and a parliament.", c: "这个国家由总统和议会共同治理。" },
  "so": { e: "I was so tired last night that I fell asleep right after dinner.", c: "昨晚我太累了，吃完晚饭就睡着了。" },
  "in": { e: "She is in the kitchen preparing lunch for the whole family.", c: "她正在厨房里给全家人准备午饭。" },
  "fundamental": { e: "Water and sunlight are fundamental to the growth of plants.", c: "水和阳光对植物生长来说至关重要。" },
  "scatter": { e: "The wind scattered the leaves all over the front yard.", c: "风把落叶吹得满院子都是。" },
  "several": { e: "I've been to that restaurant several times and the food is always good.", c: "我去过那家餐厅好几次了，菜一直不错。" },
  "flag": { e: "The national flag is raised every morning in front of the school.", c: "学校门口每天早上都升国旗。" },
  "earth": { e: "The earth revolves around the sun once every 365 days.", c: "地球每365天绕太阳转一圈。" },
  "evidence": { e: "There is no evidence to prove that he was at the scene of the crime.", c: "没有证据证明他当时在犯罪现场。" },
  "whilst": { e: "He listened to music whilst doing his homework at his desk.", c: "他一边在书桌前写作业一边听音乐。" },
  "drain": { e: "The sink is clogged and the water won't drain properly.", c: "水槽堵了，水排不下去。" },
  "mayor": { e: "The mayor attended the opening ceremony of the new public library.", c: "市长出席了新公共图书馆的开幕式。" },
  "anxiety": { e: "She felt a wave of anxiety before walking into the exam room.", c: "走进考场之前，她感到一阵焦虑。" },
  "barn": { e: "The farmer stored the hay in the old red barn behind the house.", c: "农民把干草存放在屋后那座红色旧谷仓里。" },
  "lessen": { e: "Taking a short walk can help lessen the stress of a long workday.", c: "散散步有助于缓解一整天工作带来的压力。" },
  "tutor": { e: "My parents hired a math tutor to help me prepare for the exam.", c: "我爸妈请了一个数学家教来帮我备考。" },
  "airport": { e: "We arrived at the airport two hours before the flight took off.", c: "我们在飞机起飞前两小时到达了机场。" },
  "marriage": { e: "Their marriage has lasted for over thirty happy years.", c: "他们的婚姻已经幸福地持续了三十多年。" },
  "quicken": { e: "Her heart quickened when she saw the test results on the screen.", c: "看到屏幕上显示的考试成绩时，她的心跳加快了。" },
  "everyone": { e: "Everyone in the office brought a dish to share at the party.", c: "办公室每个人都带了一道菜来聚会上分享。" },
  "cushion": { e: "She placed a soft cushion on the chair to make it more comfortable.", c: "她在椅子上放了一个软垫子，坐起来更舒服。" },
  "delicious": { e: "The soup smells absolutely delicious; what did you put in it?", c: "这汤闻起来太香了，你放了什么进去？" },
  "price": { e: "The price of vegetables has gone up a lot this month.", c: "这个月蔬菜价格涨了不少。" },
  "especially": { e: "I love all kinds of fruit, especially fresh strawberries in summer.", c: "我喜欢各种水果，尤其是夏天的新鲜草莓。" },
  "late": { e: "He stayed up late last night finishing the report for the boss.", c: "他昨晚熬夜到很晚才完成老板要的报告。" },
  "skillful": { e: "She is a very skillful driver and handles the car with ease.", c: "她是个很熟练的司机，开车非常自如。" },
  "bat": { e: "He swung the bat and hit the ball straight out of the park.", c: "他挥棒一击，把球直接打出了球场。" },
  "blackboard": { e: "The teacher wrote three key questions on the blackboard before class.", c: "上课前老师在黑板上写了三个关键问题。" },
  "accord": { e: "The two sides reached an accord after three days of negotiation.", c: "经过三天的谈判，双方达成了一项协议。" },
  "limitation": { e: "The only limitation of this phone is its short battery life.", c: "这部手机唯一的不足就是电池续航太短。" },
  "pulse": { e: "The nurse checked the patient's pulse and blood pressure first.", c: "护士先检查了病人的脉搏和血压。" },
  "upper": { e: "She lives on the upper floor of the apartment building with a nice view.", c: "她住在公寓楼的上一层，视野很好。" },
  "bound": { e: "The train is bound for Shanghai and will depart in ten minutes.", c: "这趟列车开往上海，十分钟后出发。" },
  "sink": { e: "The Titanic sank after hitting an iceberg in the North Atlantic.", c: "泰坦尼克号在北大西洋撞上冰山后沉没了。" },
  "hold": { e: "Can you hold my bag for a moment while I find my keys?", c: "你帮我拿一下包好吗？我找一下钥匙。" },
  "confuse": { e: "The two words look so similar that they often confuse beginners.", c: "这两个词看起来太像了，经常把初学者搞糊涂。" },
  "forbid": { e: "The school forbids students from using phones during class hours.", c: "学校禁止学生在上课时间使用手机。" },
  "goods": { e: "The shop delivers fresh goods to customers every morning.", c: "这家店每天早上给顾客配送新鲜商品。" },
  "infer": { e: "From her tone of voice, I inferred that she was not happy with the result.", c: "从她的语气中，我推断她对结果不满意。" },
  "trouble": { e: "I had trouble finding a parking spot near the shopping mall.", c: "我在商场附近找不到停车位，很头疼。" },
  "mould": { e: "There was green mould growing on the bread left in the cupboard.", c: "放在橱柜里的面包上长了绿色的霉菌。" },
  "rotation": { e: "The rotation of crops helps keep the soil rich and healthy.", c: "轮作有助于保持土壤肥沃和健康。" },
  "absolute": { e: "I have absolute confidence that you will pass the driving test.", c: "我百分之百相信你能通过驾照考试。" },
  "cunning": { e: "The fox is often described as a cunning animal in fairy tales.", c: "童话故事里狐狸常被描绘成狡猾的动物。" },
  "stroke": { e: "He suffered a heat stroke after working outside all afternoon.", c: "他在外面干了一下午活后中暑了。" },
  "blame": { e: "Don't blame yourself for the mistake; it could happen to anyone.", c: "别为这个错误责怪自己，谁都可能犯。" },
  "heat": { e: "The heat from the oven filled the kitchen with a warm, cozy feeling.", c: "烤箱的热气让厨房充满了温暖舒适的感觉。" },
  "stocking": { e: "She hung a red stocking by the fireplace on Christmas Eve.", c: "她在圣诞夜把一只红色长袜挂在了壁炉旁。" },
  "violin": { e: "He started learning the violin when he was only five years old.", c: "他五岁就开始学小提琴了。" },
  "derive": { e: "Many English words derive from Latin and ancient Greek.", c: "很多英语单词来源于拉丁语和古希腊语。" },
  "preposition": { e: "The word \"on\" is a preposition that indicates position or location.", c: "\"on\" 是一个表示位置或地点的介词。" },
  "file": { e: "Please save the file under your name and send it to me by email.", c: "请把文件用你的名字保存，然后发邮件给我。" },
  "sock": { e: "I can't find the other sock; it must be under the bed somewhere.", c: "我找不到另一只袜子了，肯定在床底下什么地方。" },
  "recall": { e: "I can't recall where I put my glasses after I came home last night.", c: "我想不起来昨晚回家后把眼镜放哪儿了。" },
  "composition": { e: "The teacher asked us to write a short composition about our hometown.", c: "老师让我们写一篇关于家乡的短文。" },
  "sympathy": { e: "She expressed her sympathy for the families who lost their homes in the flood.", c: "她对在洪水中失去家园的人们表示了同情。" },
  "electricity": { e: "The electricity went out during the storm, so we lit some candles.", c: "暴风雨时停电了，我们就点了些蜡烛。" },
  "birthday": { e: "My friends threw a surprise party for my twentieth birthday last week.", c: "上周我朋友为我的二十岁生日办了一个惊喜派对。" },
  "weapon": { e: "The police found a hidden weapon in the suspect's car.", c: "警察在嫌疑犯的车里发现了一件藏匿的武器。" },
  "tub": { e: "She filled the tub with warm water and added some bath salts.", c: "她把浴缸放满温水，加了点浴盐。" },
  "within": { e: "You should receive a reply within three working days after applying.", c: "提交申请后三个工作日内你应该会收到回复。" },
  "enough": { e: "One cup of rice is enough for two people to share.", c: "一杯米够两个人吃。" },
  "fever": { e: "The child had a high fever, so his mother took him to the hospital.", c: "孩子发高烧，妈妈就带他去了医院。" },
  "vessel": { e: "A small fishing vessel returned to port with a full catch of fish.", c: "一艘小渔船满载而归，回到了港口。" },
  "dot": { e: "From the top of the hill, the cars below looked like tiny moving dots.", c: "从山顶往下看，下面的汽车像一个个移动的小点。" },
  "commission": { e: "The artist received a commission to paint a mural for the city hall.", c: "那位艺术家接到了一个为市政厅画壁画的委托。" },
  "familiar": { e: "The voice on the phone sounded familiar, but I couldn't place it.", c: "电话里的声音听起来很耳熟，但我一时想不起来是谁。" },
  "expand": { e: "The company plans to expand its business into overseas markets next year.", c: "公司计划明年将业务拓展到海外市场。" },
  "conquer": { e: "She finally conquered her fear of public speaking after months of practice.", c: "经过几个月的练习，她终于克服了对公开演讲的恐惧。" },
  "instruction": { e: "Read the instructions carefully before you start assembling the desk.", c: "开始组装书桌之前，请仔细阅读说明书。" },
  "busy": { e: "I'm too busy to go out for lunch, so I'll just order a takeaway.", c: "我太忙了没空出去吃午饭，就点个外卖吧。" },
  "tolerance": { e: "Living in a big city requires tolerance of noise and crowded spaces.", c: "在大城市生活需要忍受噪音和拥挤。" },
  "revolt": { e: "The heavy taxes sparked a revolt among the local farmers.", c: "沉重的赋税引发了当地农民的起义。" },
  "circumstance": { e: "Under no circumstance should you give out your password to strangers.", c: "在任何情况下都不应该把密码告诉陌生人。" },
  "forty": { e: "She looks much younger than forty thanks to her healthy lifestyle.", c: "由于健康的生活方式，她看起来比四十岁年轻多了。" },
  "salute": { e: "The soldiers raised their hands to salute the flag during the ceremony.", c: "仪式上士兵们举手向国旗敬礼。" },
  "storey": { e: "Their new office takes up the entire third storey of the building.", c: "他们的新办公室占了整个大楼的第三层。" },
  "cube": { e: "Could you cut the tofu into small cubes for the soup?", c: "你能把豆腐切成小方块放进汤里吗？" },
  "nuclear": { e: "The country is investing heavily in nuclear energy as a clean power source.", c: "该国正大力投资核能作为清洁能源。" },
  "abundant": { e: "There is abundant evidence that regular exercise improves mental health.", c: "有大量证据表明规律运动能改善心理健康。" },
  "term": { e: "The academic term starts in September and ends in January.", c: "这个学期九月份开始，一月份结束。" },
  "complain": { e: "He went to the front desk to complain about the noise from the next room.", c: "他去前台投诉隔壁房间太吵了。" },
  "typewriter": { e: "My grandfather still keeps an old typewriter in his study upstairs.", c: "我爷爷还在楼上书房里留着一台老式打字机。" },
  "reference": { e: "You should list at least three references at the end of your paper.", c: "你的论文末尾至少应该列出三条参考文献。" },
  "crisis": { e: "The company faced a financial crisis and had to lay off many workers.", c: "公司面临财务危机，不得不裁掉很多员工。" },
  "general": { e: "In general, people in this city are very friendly to newcomers.", c: "总的来说，这个城市的人对新来的人都很友好。" },
  "musician": { e: "He dreams of becoming a professional musician and performing on stage.", c: "他梦想成为一名专业音乐家，在舞台上演出。" },
  "realize": { e: "She didn't realize how late it was until she looked at the clock.", c: "她看了一眼钟才发现已经很晚了。" },
  "silly": { e: "Don't be silly — you're not going to fail the exam just because you missed one class.", c: "别傻了——你不会因为缺了一节课就考不及格的。" },
  "liberty": { e: "People should have the liberty to express their own opinions freely.", c: "人们应该有自由表达自己观点的权利。" },
  "overnight": { e: "The temperature dropped so much overnight that the pond froze solid.", c: "一夜之间温度骤降，池塘都冻成冰了。" },
  "tend": { e: "I tend to forget things if I don't write them down in my notebook.", c: "我如果不记在笔记本上，就很容易忘事。" },
  "readily": { e: "She readily agreed to help us move the furniture on Saturday.", c: "她爽快地答应了周六帮我们搬家具。" },
  "dissatisfy": { e: "The poor quality of the product dissatisfied many loyal customers.", c: "产品质量差让很多老顾客感到不满。" },
  "front": { e: "There is a beautiful garden in front of the main entrance to the building.", c: "大楼正门前有一个漂亮的花园。" },
  "harden": { e: "The clay will harden after you leave it in the sun for a few hours.", c: "把黏土放在太阳下晒几小时就会变硬。" },
  "deep": { e: "The water in the middle of the lake is too deep to stand in.", c: "湖中央的水太深了，站不住。" },
  "full": { e: "My stomach is full; I can't eat another bite of dessert.", c: "我肚子饱了，一口甜点也吃不下了。" },
  "canoe": { e: "They paddled the canoe across the calm lake to reach the small island.", c: "他们划着独木舟穿过平静的湖面到达小岛。" },
  "steward": { e: "The steward helped passengers store their luggage in the overhead bins.", c: "乘务员帮乘客把行李放进头顶的行李舱里。" },
  "minister": { e: "The prime minister gave a speech on national television last night.", c: "首相昨晚在国家电视台上发表了讲话。" },
  "aloud": { e: "She read the poem aloud to the class with a clear and gentle voice.", c: "她用清晰温柔的声音向全班朗读了那首诗。" },
  "auto": { e: "The auto industry is shifting toward electric and self-driving vehicles.", c: "汽车行业正在向电动和自动驾驶汽车转型。" },
  "moisture": { e: "The moisture in the air makes the room feel stuffy in summer.", c: "夏天空气中的湿气让房间感觉很闷。" },
  "suburb": { e: "They moved to a quiet suburb to raise their children away from the city noise.", c: "他们搬到了安静的郊区，远离城市喧嚣来抚养孩子。" },
  "monument": { e: "The monument was built to honor the soldiers who died in the war.", c: "这座纪念碑是为纪念在战争中牺牲的士兵而建的。" },
  "lid": { e: "Please put the lid back on the jar so the cookies don't go soft.", c: "请把罐子的盖子盖回去，不然饼干会变软。" },
  "decent": { e: "He earns a decent salary and can afford a comfortable life for his family.", c: "他收入不错，能负担起一家人舒适的生活。" },
  "sixteen": { e: "She got her first part-time job at the age of sixteen to save for college.", c: "她十六岁时打了第一份零工，为上大学存钱。" },
  "listener": { e: "She is a good listener; you can always talk to her about your problems.", c: "她是个很好的倾听者，你总能跟她聊聊自己的烦恼。" },
  "unite": { e: "The whole community united to help the families affected by the flood.", c: "整个社区团结起来帮助受洪灾影响的家庭。" },
  "death": { e: "The sudden death of his pet dog left him heartbroken for weeks.", c: "他的宠物狗突然去世，让他伤心了好几个星期。" },
  "aviation": { e: "The aviation industry has made air travel safer and more affordable over the years.", c: "航空业多年来让空中旅行变得更安全也更便宜。" },
  "subtract": { e: "If you subtract five from twelve, you get seven.", c: "十二减去五等于七。" },
  "therefore": { e: "He didn't study for the test; therefore, he failed it badly.", c: "他没有复习，所以考试考得很差。" },
  "engine": { e: "The car's engine started making a strange noise on the highway.", c: "汽车发动机在高速公路上开始发出奇怪的声音。" },
  "poem": { e: "She wrote a short poem for her mother on Mother's Day.", c: "母亲节那天她给妈妈写了一首短诗。" },
  "gasoline": { e: "The price of gasoline has gone up by nearly ten percent this month.", c: "这个月汽油价格涨了将近百分之十。" },
  "railroad": { e: "The railroad connects the two major cities and cuts travel time in half.", c: "这条铁路连接了两个大城市，把出行时间缩短了一半。" },
  "honey": { e: "I like to add a spoonful of honey to my tea instead of sugar.", c: "我喜欢在茶里加一勺蜂蜜，而不是放糖。" },
  "variety": { e: "The supermarket offers a wide variety of fresh fruits all year round.", c: "这家超市全年供应种类丰富的新鲜水果。" },
  "represent": { e: "Each color on the chart represents a different category of spending.", c: "图表上的每种颜色代表不同的支出类别。" },
  "next": { e: "The next bus to the city center will arrive in about ten minutes.", c: "去市中心的下一班公交车大约十分钟后到。" },
  "argument": { e: "We had a small argument about where to go for dinner, but we sorted it out quickly.", c: "我们为去哪儿吃饭吵了一小架，但很快就解决了。" },
  "turbine": { e: "The wind turbine spins faster when the wind blows strongly across the field.", c: "当强风吹过田野时，风力涡轮机转得更快。" },
  "finding": { e: "The key finding of the survey is that most people prefer online shopping now.", c: "这项调查的主要发现是现在大多数人更喜欢网购。" },
  "them": { e: "I bought some apples and put them in the fridge for later.", c: "我买了些苹果，把它们放进冰箱里留着以后吃。" },
  "fare": { e: "The bus fare in this city is only two yuan per ride.", c: "这个城市的公交车票只要两块钱一趟。" },
  "embrace": { e: "She ran to the door to embrace her father after he came home from work.", c: "爸爸下班回家后，她跑到门口拥抱了他。" },
  "curious": { e: "The little girl was curious about the stars and kept asking her dad questions.", c: "小女孩对星星很好奇，不停地问她爸爸问题。" },
  "butcher": { e: "I went to the butcher to buy some fresh chicken for tonight's dinner.", c: "我去肉铺买了些新鲜鸡肉做今晚的晚餐。" },
  "ampere": { e: "The fuse is rated at 15 amperes to protect the household circuit.", c: "保险丝的额定电流是15安培，用来保护家用电路。" },
  "zero": { e: "The temperature dropped to nearly zero degrees during the night.", c: "夜里温度降到了将近零度。" },
  "shut": { e: "Please shut the window before you leave; it looks like it might rain.", c: "你走之前请关上窗户，看起来要下雨了。" },
  "enforce": { e: "The police are responsible for enforcing traffic laws on the highway.", c: "警察负责在高速公路上执行交通法规。" },
  "socialism": { e: "The country adopted socialism as its guiding political and economic system.", c: "该国将社会主义作为其指导性的政治经济制度。" },
  "southwest": { e: "The wind is blowing from the southwest, bringing warm and humid air.", c: "风从西南方向吹来，带来了温暖潮湿的空气。" },
  "queen": { e: "The queen waved to the crowd from the balcony of the palace.", c: "女王从王宫的阳台上向人群挥手致意。" },
  "chocolate": { e: "She broke off a piece of dark chocolate and handed it to her friend.", c: "她掰了一块黑巧克力递给朋友。" },
  "hopeless": { e: "He felt hopeless after failing the driving test for the third time.", c: "第三次驾照考试又没过，他觉得彻底没希望了。" },
  "empire": { e: "The Roman Empire once stretched across much of Europe and North Africa.", c: "罗马帝国曾经横跨欧洲和北非的广大地区。" },
  "suggestion": { e: "Thanks for the suggestion — I'll try that restaurant next time.", c: "谢谢你的建议，下次我去试试那家餐厅。" },
  "wrap": { e: "Could you help me wrap this gift for my mom's birthday?", c: "你能帮我包一下给我妈的生日礼物吗？" },
  "swing": { e: "The kids love to swing back and forth on the playground after school.", c: "孩子们放学后喜欢在操场上荡秋千。" },
  "animal": { e: "She has always loved animals and wants to become a vet someday.", c: "她一直很喜欢动物，希望有一天能成为一名兽医。" },
  "enclose": { e: "Please enclose a copy of your ID with the application form.", c: "请在申请表里附上一份身份证复印件。" },
  "kind": { e: "It was very kind of you to help the old lady carry her groceries home.", c: "你帮那位老太太把东西拎回家，真是太善良了。" },
  "nuisance": { e: "The construction noise outside has become a real nuisance for the whole neighborhood.", c: "外面的施工噪音已经成了整个小区的大麻烦。" },
  "optical": { e: "He bought an optical mouse to replace the old one that stopped working.", c: "他买了一个光电鼠标来替换那个坏掉的旧鼠标。" },
  "influence": { e: "Her older sister had a great influence on her decision to study medicine.", c: "她姐姐对她学医的决定影响很大。" },
  "competition": { e: "The competition for this job is fierce, with over 200 applicants.", c: "这个职位的竞争很激烈，有两百多人申请。" },
  "thrill": { e: "It was a real thrill to see my favorite band perform live on stage.", c: "看到我最喜欢的乐队现场表演，真是太激动了。" },
  "niece": { e: "My niece just turned three and she already knows the whole alphabet song.", c: "我侄女刚满三岁，已经会唱整首字母歌了。" },
  "gallon": { e: "The car's fuel tank can hold about fifteen gallons of gasoline.", c: "这辆车的油箱大约能装十五加仑汽油。" },
  "seller": { e: "The seller offered a discount if I bought more than three items at once.", c: "如果我一次买三件以上，卖家就给打折。" },
  "dismiss": { e: "The boss decided to dismiss the employee for repeatedly being late to work.", c: "老板决定开除那个多次上班迟到的员工。" },
  "fertile": { e: "The soil near the river is very fertile and perfect for growing vegetables.", c: "河边的土壤非常肥沃，很适合种蔬菜。" },
  "soon": { e: "The movie will start soon, so let's go find our seats now.", c: "电影马上要开始了，我们去找座位吧。" },
  "breast": { e: "He held the crying baby close to his breast to calm her down.", c: "他把哭闹的宝宝紧紧抱在胸前安抚她。" },
  "forehead": { e: "She felt his forehead to check if he had a fever before school.", c: "上学前她摸了摸他的额头，看看有没有发烧。" },
  "hurry": { e: "We'd better hurry up if we want to catch the last train home.", c: "要是想赶上末班车回家，我们最好快点。" },
  "probably": { e: "It will probably rain later this afternoon, so take an umbrella just in case.", c: "下午很可能会下雨，带把伞以防万一。" },
  "cloud": { e: "A dark cloud covered the sun and the temperature dropped suddenly.", c: "一片乌云遮住了太阳，气温突然降了下来。" },
  "relate": { e: "I can really relate to the main character's struggle in this movie.", c: "我真的很能理解这部电影里主角的挣扎。" },
  "timetable": { e: "Check the bus timetable online before you leave, so you don't have to wait long.", c: "出发前上网查一下公交时刻表，免得等太久。" },
  "famous": { e: "The restaurant became famous for its handmade dumplings and spicy sauce.", c: "这家餐厅以手工饺子和辣酱闻名。" },
  "dog": { e: "She takes her dog for a walk in the park every morning before breakfast.", c: "她每天早上吃早饭前都带狗狗去公园散步。" },
  "brow": { e: "He wiped the sweat from his brow after carrying the heavy box upstairs.", c: "把重箱子搬上楼后，他擦了擦额头上的汗。" },
  "even": { e: "Even though he was tired, he stayed up late to help his son with homework.", c: "尽管很累，他还是熬夜帮儿子辅导作业。" },
  "title": { e: "What's the title of the book you borrowed from the library last week?", c: "你上周从图书馆借的那本书叫什么名字？" },
  "obviously": { e: "She was obviously upset about something, but she didn't want to talk about it.", c: "她显然在为什么事情不开心，但不想说。" },
  "monitor": { e: "The teacher asked me to monitor the classroom while she stepped out for a moment.", c: "老师让我在她出去一会儿时照看一下教室。" },
  "robe": { e: "She put on a warm bathrobe after getting out of the shower.", c: "洗完澡后她穿上了一件暖和的浴袍。" },
  "impossible": { e: "It's almost impossible to find a seat on the subway during rush hour.", c: "高峰期在地铁上几乎不可能找到座位。" },
  "oral": { e: "The students have to take an oral exam at the end of the semester.", c: "学生期末要参加一个口语考试。" },
  "butter": { e: "Spread some butter on the toast while it's still warm and crispy.", c: "趁吐司还热乎酥脆的时候抹上黄油。" },
  "former": { e: "She still keeps in touch with her former colleagues from the old company.", c: "她还跟以前公司的老同事保持联系。" },
  "this": { e: "This is the first time I've ever been to this part of the city.", c: "这是我第一次来这个城市的这个区域。" },
  "count": { e: "You can count on me to help you move this weekend.", c: "这周末搬家你可以指望我来帮忙。" },
  "tribe": { e: "The tribe has lived in the Amazon rainforest for thousands of years.", c: "这个部落已经在亚马逊雨林里生活了几千年。" },
  "cheerful": { e: "She always has a cheerful smile on her face, even on rainy mornings.", c: "即使在雨天的早晨，她脸上也总是挂着开朗的笑容。" },
  "art": { e: "She is studying art history at the university and hopes to work in a museum.", c: "她在大学读艺术史，希望以后能在博物馆工作。" },
  "politics": { e: "We try to avoid talking about politics at family dinners to keep the peace.", c: "为了保持和气，我们尽量不在家庭聚餐时谈政治。" },
  "sigh": { e: "He let out a deep sigh of relief when he saw his lost dog come home.", c: "看到走丢的狗回到家，他长长地松了一口气。" },
  "expose": { e: "Don't expose your skin to direct sunlight for too long without sunscreen.", c: "不涂防晒霜的话，别让皮肤在太阳底下晒太久。" },
  "sleeve": { e: "She rolled up her sleeves and started washing the dishes right away.", c: "她卷起袖子立刻开始洗碗。" },
  "courage": { e: "It takes real courage to stand up and admit you made a mistake.", c: "站出来承认自己犯了错需要很大的勇气。" },
  "sex": { e: "The form asks for your name, age, sex, and contact information.", c: "表格要求填写姓名、年龄、性别和联系方式。" },
  "stoop": { e: "He had to stoop down to get through the low doorway of the old house.", c: "他得弯下腰才能穿过老房子那个矮门框。" },
  "organization": { e: "She works for a nonprofit organization that helps homeless families find housing.", c: "她在一家帮助无家可归者找房子的非营利组织工作。" },
  "confine": { e: "The patient was confined to bed for a week after the surgery on his knee.", c: "膝盖手术后，病人被要求卧床一周。" },
  "cheese": { e: "Could you add extra cheese to my pizza when you order it?", c: "你点披萨的时候能帮我多加一份芝士吗？" },
  "problem": { e: "The biggest problem with this phone is that the battery drains way too fast.", c: "这部手机最大的问题是电池耗得太快了。" },
  "rusty": { e: "The old bicycle chain had become rusty after sitting in the rain for months.", c: "旧自行车链条在雨里放了几个月后生锈了。" },
  "devise": { e: "The team devised a new strategy to reduce waste in the production process.", c: "团队设计了一种新策略来减少生产过程中的浪费。" },
  "some": { e: "Would you like some milk in your coffee, or do you prefer it black?", c: "你咖啡里要加点牛奶吗，还是喝纯的？" },
  "reporter": { e: "The reporter interviewed several local residents about the new traffic policy.", c: "记者就新交通政策采访了几位当地居民。" },
  "return": { e: "I'll return the book to the library as soon as I finish reading it.", c: "我一看完这本书就还给图书馆。" },
  "fridge": { e: "There's nothing in the fridge except some eggs and a carton of milk.", c: "冰箱里除了几个鸡蛋和一盒牛奶什么都没有。" },
  "director": { e: "The director of the film gave a short speech before the opening night.", c: "电影放映前，导演在首映之夜作了简短的致辞。" },
  "slogan": { e: "The advertising slogan of the brand is easy to remember and quite catchy.", c: "这个品牌的广告语好记又顺口。" },
  "mere": { e: "It took him a mere ten minutes to fix the broken computer.", c: "他只花了区区十分钟就把坏电脑修好了。" },
  "idle": { e: "He spent the whole afternoon idle, just lying on the sofa watching videos.", c: "他整个下午都闲着，躺在沙发上刷视频。" },
  "self": { e: "You need to take care of yourself first before you can help others.", c: "在帮别人之前，你得先照顾好自己。" },
  "indifferent": { e: "She seemed completely indifferent to the criticism and just shrugged her shoulders.", c: "面对批评她似乎完全不在乎，只是耸了耸肩。" },
  "crowd": { e: "A large crowd gathered in the square to watch the fireworks display.", c: "一大群人聚集在广场上观看烟花表演。" },
  "tone": { e: "I don't like the tone of your voice when you speak to your little sister.", c: "我不喜欢你跟妹妹说话时的那种语气。" },
  "amount": { e: "The total amount of the bill came to 350 yuan including tax and service charge.", c: "账单总额连税和服务费一共是350元。" },
  "continent": { e: "Australia is both a country and a continent, surrounded entirely by ocean.", c: "澳大利亚既是一个国家也是一个被海洋环绕的大洲。" },
  "asian": { e: "She is a big fan of Asian food, especially Japanese and Thai dishes.", c: "她特别喜欢亚洲菜，尤其是日本料理和泰国菜。" },
  "aboard": { e: "All passengers must be aboard the plane at least thirty minutes before takeoff.", c: "所有乘客必须在起飞前至少三十分钟登机。" },
  "claw": { e: "The cat scratched the sofa with its sharp claws again last night.", c: "那只猫昨晚又用它的尖爪子挠了沙发。" },
  "whirl": { e: "The fallen leaves were caught in a whirl of wind and danced across the street.", c: "落叶被一阵旋风卷起，在街上飞舞。" },
  "liberal": { e: "He has a very liberal attitude toward different cultures and lifestyles.", c: "他对不同的文化和生活方式持非常开放的态度。" },
  "medal": { e: "She won a gold medal in the 100-meter race at the school sports meet.", c: "她在校运会的百米赛跑中赢得了一枚金牌。" },
  "child": { e: "The child held his mother's hand tightly while crossing the busy street.", c: "过繁忙的马路时，孩子紧紧抓着妈妈的手。" },
  "hair": { e: "I need to get my hair cut this weekend; it's getting way too long.", c: "我这周末得去理发，头发长得太长了。" },
  "wealth": { e: "True wealth is not just about money, but also about health and happiness.", c: "真正的财富不只是钱，还包括健康和幸福。" },
  "misunderstand": { e: "I think you misunderstood what I said earlier; let me explain it again.", c: "我觉得你刚才误解了我的意思，我再解释一遍。" },
  "supper": { e: "We usually have supper around seven o'clock after everyone gets home from work.", c: "我们一般在七点左右全家都下班回家后吃晚饭。" },
  "foreign": { e: "He speaks three foreign languages, including English, French, and German.", c: "他会说三门外语，包括英语、法语和德语。" },
  "one": { e: "One of the reasons I like this café is the quiet atmosphere and soft music.", c: "我喜欢这家咖啡馆的原因之一是这里安静的氛围和轻柔的音乐。" },
  "ax": { e: "He used an ax to chop the fallen tree into small pieces for firewood.", c: "他用斧头把倒下的树劈成小块当柴火。" },
  "deduce": { e: "From the tire marks on the road, the officer deduced the car was speeding.", c: "警察从路上的轮胎痕迹推断那辆车超速了。" },
  "comb": { e: "She ran a comb through her tangled hair before tying it into a ponytail.", c: "她把打结的头发梳顺后扎了个马尾。" },
  "date": { e: "What's the exact date of your flight to Shanghai next week?", c: "你下周飞上海的航班具体是几号？" },
  "cupboard": { e: "He opened the kitchen cupboard but found nothing except a packet of instant noodles.", c: "他打开厨房碗柜，发现除了一包方便面什么都没有。" },
  "digest": { e: "It takes the body several hours to fully digest a heavy, fatty meal.", c: "身体需要好几个小时才能完全消化一顿油腻的大餐。" },
  "six": { e: "I have six classes this semester, and the busiest day is Wednesday.", c: "我这学期有六门课，最忙的是周三。" },
  "income": { e: "She took a part-time job to supplement her monthly income while studying abroad.", c: "她在留学期间打了一份零工来补贴月收入。" },
  "echo": { e: "His voice echoed through the empty hallway as he called out her name.", c: "他喊她的名字时，声音在空荡荡的走廊里回荡。" },
  "temper": { e: "He has a quick temper, but he usually calms down after a few deep breaths.", c: "他脾气来得快，但深呼吸几下通常就能冷静下来。" },
  "scissors": { e: "Could you pass me the scissors? I need to cut off this loose thread on my shirt.", c: "能把剪刀递给我吗？我要剪掉衬衫上的这根线头。" },
  "stick": { e: "He used a long stick to reach the ball that had rolled under the car.", c: "他用一根长棍把滚到车底下的球够了出来。" },
  "weekend": { e: "What are your plans for the weekend? Want to go hiking with me?", c: "你周末有什么安排？要不要跟我一起去爬山？" },
  "physics": { e: "Physics was his favorite subject in high school because he loved doing experiments.", c: "物理是他高中最喜欢的科目，因为他喜欢做实验。" },
  "anger": { e: "He tried hard to control his anger when the customer started yelling at him.", c: "当顾客开始对他大喊大叫时，他努力克制住了怒火。" },
  "lay": { e: "She laid the baby gently in the crib and turned off the light.", c: "她把宝宝轻轻放在婴儿床里，关上了灯。" },
  "raise": { e: "The company decided to raise everyone's salary by five percent this year.", c: "公司决定今年给所有人涨百分之五的工资。" },
  "cotton": { e: "This shirt is made of pure cotton, so it feels soft on the skin.", c: "这件衬衫是纯棉的，穿在皮肤上很柔软。" },
  "mystery": { e: "The disappearance of the cat remains a mystery to the whole family.", c: "那只猫的失踪对这家人来说至今还是个谜。" },
  "fox": { e: "A fox crossed the road right in front of our car late last night.", c: "昨晚深夜一只狐狸从我们车前穿过了马路。" },
  "check": { e: "Let me check the weather forecast before we head out for the picnic.", c: "我去野餐前先查一下天气预报。" },
  "stranger": { e: "My mom always told me never to open the door to a stranger when home alone.", c: "我妈总是跟我说一个人在家时别给陌生人开门。" },
  "artistic": { e: "She has an artistic eye for color and can match clothes beautifully.", c: "她对色彩有艺术眼光，能把衣服搭配得很漂亮。" },
  "laser": { e: "The doctor used a laser to perform the eye surgery with great precision.", c: "医生用激光非常精确地进行了眼部手术。" },
  "fifth": { e: "He finished in fifth place in the marathon, just one spot short of a medal.", c: "他在马拉松中得了第五名，只差一个名次就能拿奖牌了。" },
  "filter": { e: "You should change the water filter in the kitchen every three months.", c: "厨房净水器的滤芯应该每三个月换一次。" },
  "herd": { e: "A herd of cows was grazing peacefully in the green field by the river.", c: "一群奶牛在河边绿草地上安静地吃草。" },
  "generally": { e: "People in this neighborhood are generally friendly and willing to help each other.", c: "这个小区的人一般都挺友好，愿意互相帮忙。" },
  "urge": { e: "I had a sudden urge to call my grandmother and hear her voice.", c: "我突然特别想给奶奶打个电话，听听她的声音。" },
  "admit": { e: "You should admit your mistake instead of trying to cover it up.", c: "你应该承认错误，而不是试图掩盖。" },
  "long": { e: "The meeting was so long that I nearly fell asleep in the middle of it.", c: "会议太长了，我差点中途睡着了。" },
  "begin": { e: "Let's begin the class with a quick review of what we learned last time.", c: "我们先用几分钟回顾上节课的内容，然后开始上课。" },
  "pound": { e: "She bought a pound of fresh strawberries at the farmers' market this morning.", c: "她今早在农贸市场买了一磅新鲜草莓。" },
  "dictionary": { e: "If you don't know the word, look it up in the dictionary right now.", c: "不认识这个词的话，现在就去查字典。" },
  "heroic": { e: "The firefighter's heroic act saved three children from the burning building.", c: "消防员的英勇行为从着火的大楼里救出了三个孩子。" },
  "of": { e: "What's the name of the restaurant you recommended to me last week?", c: "你上周给我推荐的那家餐厅叫什么名字来着？" },
  "preceding": { e: "The preceding chapter explains the basic concepts you need to understand first.", c: "前一章解释了你需要先理解的基本概念。" },
  "pollution": { e: "Air pollution in big cities can cause serious breathing problems over time.", c: "大城市的空气污染时间长了会导致严重的呼吸问题。" },
  "sunrise": { e: "We woke up at five to watch the sunrise from the top of the mountain.", c: "我们五点就起来去山顶看日出。" },
  "lighten": { e: "She told a funny joke to lighten the mood during the tense meeting.", c: "在紧张会议中她讲了个笑话来缓和气氛。" },
  "false": { e: "The rumor turned out to be false, and everyone felt relieved when they heard the truth.", c: "那个谣言后来被证明是假的，大家知道真相后都松了一口气。" },
  "ache": { e: "My legs ache after standing in line for three hours at the concert.", c: "在演唱会排了三小时队后，我的腿疼得要命。" },
  "mouthful": { e: "He took a big mouthful of water after running three laps around the track.", c: "沿着操场跑了三圈后，他喝了一大口水。" },
  "cancel": { e: "We had to cancel the outdoor event because of the thunderstorm warning.", c: "因为有雷暴预警，我们不得不取消户外活动。" },
  "hall": { e: "Please wait in the hall on the first floor until someone calls your name.", c: "请在一楼大厅等候，直到有人叫你的名字。" },
  "leader": { e: "A good leader listens to the team before making important decisions.", c: "一个好的领导在做重要决策之前会先听取团队的意见。" },
  "mill": { e: "The old flour mill by the river has been turned into a popular local museum.", c: "河边那座老面粉厂已经被改造成了一家受欢迎的本地博物馆。" },
  "assign": { e: "The teacher assigned each student a different topic for the final presentation.", c: "老师给每个学生分配了不同的期末演讲主题。" },
  "sort": { e: "What sort of music do you usually listen to when you're studying or working?", c: "你学习或工作的时候一般听什么样的音乐？" },
  "miracle": { e: "It was a miracle that nobody was hurt in such a serious car crash.", c: "这么严重的车祸竟然没人受伤，真是一个奇迹。" },
  "eliminate": { e: "We need to eliminate all the spelling errors before submitting the final draft.", c: "提交终稿之前我们需要消除所有的拼写错误。" },
  "bird": { e: "A little bird built its nest in the tree right outside my bedroom window.", c: "一只小鸟在我卧室窗外的树上筑了巢。" },
  "france": { e: "She spent a summer studying French in a small town in southern France.", c: "她在法国南部的一个小镇度过了一个夏天学习法语。" },
  "orbit": { e: "The satellite was successfully placed into orbit around the Earth last Tuesday.", c: "那颗卫星上周二被成功送入环绕地球的轨道。" },
  "mute": { e: "I usually put my phone on mute during meetings so it doesn't disturb anyone.", c: "开会时我通常把手机调成静音，免得打扰别人。" },
  "purity": { e: "The purity of the water from this mountain spring is tested every month.", c: "这个山泉的水质纯净度每月都会检测。" },
  "despise": { e: "She despises people who are rude to waiters and service workers in restaurants.", c: "她鄙视那些对餐厅服务员粗鲁的人。" },
  "military": { e: "He joined the military right after graduating from high school at eighteen.", c: "他高中毕业后十八岁就参军了。" },
  "refusal": { e: "His refusal to answer any more questions made the whole situation look suspicious.", c: "他拒绝再回答任何问题，让整个情况看起来很可疑。" },
  "provision": { e: "The school made special provisions for students with learning difficulties during exams.", c: "学校在考试期间为学习有困难的学生做了特别安排。" },
  "rub": { e: "She rubbed her hands together to warm them up in the freezing cold wind.", c: "在刺骨寒风中她搓着双手来取暖。" },
}
module.exports = CURATED
